version: "3.9"

services:
  pgvector:
    image: pgvector/pgvector:pg17

    container_name: pgvector

    restart: always

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajjan

    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data: